### ISSUE TITLE
day of week with L

### ISSUE THREAD

**Issue by innominate227** [jcoutch/NCrontab-Advanced#1]
"0 0 * * 0L" - works as i expect last sunday of the month
"0 0 * * SUNL" - I would expect to be the same but returns every sunday of the month

https://dotnetfiddle.net/0zwqCS

**Comment by jcoutch** [comment]
Thanks for identifying this @innominate227!  I have added test cases and resolved the issue.  I'm in the process of fixing some other issues regarding time zone support, and will push a new package in the next day or so.
