### ISSUE TITLE
Incrementing from 58 seconds/minutes skips 59 seconds/minutes

### ISSUE THREAD

**Issue by gerrod** [jcoutch/NCrontab-Advanced#15]
There's currently a bug in the latest release of NCrontab-Advanced where advancing from 58 seconds/minutes skips over 59 seconds/minutes.

I've [submitted a PR to fix this bug](https://github.com/jcoutch/NCrontab-Advanced/pull/14) some months ago - just wondering if you've had a chance to verify this?

Cheers.

**Comment by jcoutch** [comment]
Hi @gerrod!  I remembered seeing the PR a while back, didn't have time to review it, and with how crazy my schedule has been, completely forgot about it.  I'll try to get to it this week!

**Comment by jcoutch** [comment]
@gerrod - I sincerely apologize for not getting to this until now...life has been crazy lately!  The merge request looks good, and I'll publish a new package today!

**Comment by jcoutch** [comment]
The new package has been published:
https://www.nuget.org/packages/NCrontab.Advanced/1.3.15

**Comment by gerrod** [comment]
Awesome, thanks!!
