### ISSUE TITLE
Last hour in range gets skipped

### ISSUE THREAD

**Issue by tw17** [jcoutch/NCrontab-Advanced#20]
There's currently a bug in the latest release of NCrontab-Advanced where the last hour in a range gets skipped

I've [submitted a PR to fix this bug](https://github.com/jcoutch/NCrontab-Advanced/pull/19)

Cheers.

**Comment by jcoutch** [comment]
Thanks for the pull request!  It's merged, and I queued up a deploy of 1.3.21.
https://ci.appveyor.com/project/jcoutch/ncrontab-advanced/builds/24819745
