### ISSUE TITLE
.net core support targets wrong framework

### ISSUE THREAD

**Issue by rposener** [jcoutch/NCrontab-Advanced#6]
Hi,  Just tried to pull in the library for .net core support.  Looks like it targets netstandard1.5, not the "final" release of "netstandard1.6".

**Comment by rposener** [comment]
The relatively easy, although should be unnecessary work-around is to import the netstandard1.5 like this in project.json:

`"frameworks": {
    "netstandard1.6": {
      "imports": [
        "dnxcore50",
        "netstandard1.5"
      ]
    }
  }`

**Comment by jcoutch** [comment]
I didn't catch that in your original merge request.  I'll change it and re-deploy the nuget package during lunch.

**Comment by jcoutch** [comment]
@rposener - Did that resolve your issue?

**Comment by rposener** [comment]
Perfect!  Thanks - I removed the work-around.  Great library by the way.
