### ISSUE TITLE
TimeZone support

### ISSUE THREAD

**Issue by crawdell** [jcoutch/NCrontab-Advanced#9]
I need my users to be able to set their cron schedules in their preferred time zone instead of using the server's current time zone.  Is there a way to use GetNextOccurrence with a time zone to have it return the proper next occurrence in a specified time zone?

**Comment by crawdell** [comment]
I think maybe I can handle timezone without modification of NCrontab-Advanced.  

My idea is to convert the current server datetime to the current datetime in the user's timezone (TimeZoneInfo.ConvertTime method).  This will give me the current datetime in the users timezone as a starting point and then the cron schedule will be applied in GetNextOccurrence to return the next possible datetime within that timezone because of using the proper starting point. 

 I guess in this way, NCrontab-Advanced doesn't need to be timezone aware to make this work.  

I will test this idea and report back in case others find this useful.

**Comment by jcoutch** [comment]
That will work in most cases, but you may run into issues with times scheduled during the 1-hour offset at the end of Daylight Saving Time (i.e. if your server time is EST, but someone is accessing your site from UTC.)  Just something to keep in mind.

**Comment by jcoutch** [comment]
Since I haven't heard back since January, I'm going to close this bug.  If you do find that you need TimeZone support, and you don't require year support in your cron strings, it looks like Hangfire's new Cronos parsing engine supports it:

https://github.com/HangfireIO/Cronos

**Comment by crawdell** [comment]
Thanks for the follow up.  I've been able to use TimeZoneInfo.ConvertTime with some code to handle schedules at the end of DST as you pointed out above.  It works for my situation.  I'll take a look at Hangfire's implementation to see if there is any merit in trying to use it.
